#!/usr/bin/env python3
"""Batch job 3: autogenerated Spark job for API execution tests."""
import argparse
import logging
import os
import sys

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

JOB_NUMBER = 3
JOB_ID = os.getenv("JOB_ID", "local-dev")

logging.basicConfig(
    level=logging.INFO,
    format=f"%(asctime)s [%(levelname)s] [job_id={JOB_ID}] [job_3] %(message)s",
)
logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=f"Lakehouse batch Spark job {JOB_NUMBER}")
    parser.add_argument("--records", type=int, default=1200)
    parser.add_argument("--tag", type=str, default="batch10")
    return parser.parse_args()


def create_base_df(spark: SparkSession, n: int):
    rows = [
        (x, float((x % 53) + 1), x % 7, f"cat_{x % 4}")
        for x in range(1, n + 1)
    ]
    return spark.createDataFrame(rows, "id long, amount double, grp int, category string")


def run_variant(df):
    if JOB_NUMBER == 1:
        return df.groupBy("grp").agg(
            F.count("*").alias("rows"),
            F.round(F.sum("amount"), 2).alias("amount_sum"),
        )

    if JOB_NUMBER == 2:
        return df.filter((F.col("id") % 2) == 0).groupBy("category").agg(
            F.round(F.avg("amount"), 3).alias("avg_amount")
        )

    if JOB_NUMBER == 3:
        return df.select("category").distinct().orderBy("category")

    if JOB_NUMBER == 4:
        return (
            df.withColumn(
                "amount_band",
                F.when(F.col("amount") < 20, F.lit("low"))
                .when(F.col("amount") < 40, F.lit("mid"))
                .otherwise(F.lit("high")),
            )
            .groupBy("amount_band")
            .count()
        )

    if JOB_NUMBER == 5:
        map_df = df.sparkSession.createDataFrame(
            [(0, "g0"), (1, "g1"), (2, "g2"), (3, "g3"), (4, "g4"), (5, "g5"), (6, "g6")],
            "grp int, grp_label string",
        )
        return df.join(map_df, on="grp", how="left").groupBy("grp_label").agg(
            F.count("*").alias("rows")
        )

    if JOB_NUMBER == 6:
        return df.withColumn("amount_tax", F.round(F.col("amount") * F.lit(1.18), 2)).agg(
            F.min("amount_tax").alias("min_taxed"),
            F.max("amount_tax").alias("max_taxed"),
        )

    if JOB_NUMBER == 7:
        return df.groupBy().agg(
            F.expr("percentile_approx(amount, 0.5)").alias("median_amount")
        )

    if JOB_NUMBER == 8:
        return df.groupBy("grp").pivot("category").count().na.fill(0)

    if JOB_NUMBER == 9:
        return (
            df.withColumn("id_str", F.col("id").cast("string"))
            .withColumn("id_len", F.length("id_str"))
            .groupBy("id_len")
            .count()
        )

    if JOB_NUMBER == 10:
        return df.groupBy("grp").agg(F.collect_set("category").alias("categories"))

    raise RuntimeError(f"Unsupported job number: {JOB_NUMBER}")


def main() -> int:
    args = parse_args()
    spark = SparkSession.builder.appName(f"lakehouse-batch10-job-{JOB_NUMBER}-{JOB_ID}").getOrCreate()

    try:
        logger.info("Starting Spark job variant=%s records=%s tag=%s", JOB_NUMBER, args.records, args.tag)
        base_df = create_base_df(spark, args.records)
        result_df = run_variant(base_df)

        result_rows = result_df.count()
        output_path = f"s3a://lakehouse-raw/job-runs/job_{JOB_NUMBER}/job_id={JOB_ID}/"
        result_df.coalesce(1).write.mode("overwrite").json(output_path)

        logger.info("Result rows: %s", result_rows)
        logger.info("Output path: %s", output_path)
        logger.info("Job %s completed successfully", JOB_NUMBER)
        return 0
    except Exception as exc:
        logger.error("Job %s failed: %s", JOB_NUMBER, exc, exc_info=True)
        return 1
    finally:
        spark.stop()
        logger.info("Spark session stopped")


if __name__ == "__main__":
    sys.exit(main())
